remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ECG Dilineater and Compressor
description: Course Project for EE 338: Digital Signal Processing done in Autumn 2020 at IIT Bombay.
show_downloads: true
